# 网络
networks:
  work-network:
    name: work-network

# 服务(服务名称、运行说明、镜像文件、容器名称、启动方式、网络端口、存储方式、环境变量、启动指令、设主程序、默认参数、资源控制)
services:
  work-mysql:
    image: mysql:8.0.41
    container_name: work-mysql
    restart: always
    networks:
      - work-network
    ports:
      - "3306:3306"
    volumes:
      - "./work-basic-component/work-mysql/memory/:/var/lib/mysql/" # 持久目录
      - "./work-basic-component/work-mysql/share/:/share" # 共享目录
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Qwe54188_

  work-redis:
    image: redis:7.4.2
    container_name: work-redis
    restart: always
    networks:
      - work-network
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: Qwe54188_ # 这个设置好像没有什么用
    volumes:
      - "./work-basic-component/work-redis/memory/:/var/lib/redis/" # 持久目录
      - "./work-basic-component/work-redis/share/:/share" # 共享目录

  work-ollama:
    # NOTE: 安装 ollama 后如果需要支持 GPU 则需要做以下操作
    # $ curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \
    #    | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    # $ curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \
    #    | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
    #    | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
    # $ sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
    # $ sudo nvidia-ctk runtime configure --runtime=docker && sudo systemctl restart docker
    # 然后重新运行集群即可
    image: ollama/ollama
    container_name: work-ollama
    restart: "always"
    networks:
      - work-network
    ports:
      - "11434:11434"
    volumes:
      - "./work-basic-component/work-ollama:/root/.ollama"
    entrypoint:
      - "/bin/ollama"
    command:
      - "serve"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  work-nacos:
    # NOTE: Nacos 貌似没有环境变量可以直接初始化用户密码, 因此最好不要彻底重启 Nacos, 否则权限验证会失效
    image: nacos/nacos-server:v2.5.1
    container_name: work-nacos
    restart: always
    networks:
      - work-network
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      MODE: standalone # 单机部署模式
      NACOS_AUTH_TOKEN: au3y/JinInzSQu5hxaQQSiyvN3kMcfgOLcFRA4AHrUE= # 使用 openssl rand -base64 32 生成
      NACOS_AUTH_IDENTITY_KEY: username
      NACOS_AUTH_IDENTITY_VALUE: root
      NACOS_AUTH_ENABLE: true # 开启权限系统

  work-sentinel:
    # NOTE: 由于官方没有制作为镜像文件因此需要我们自己制作
    build:
      context: ./work-basic-component/work-sentinel/
      dockerfile: Dockerfile
    image: sentinel:1.8.6
    restart: always
    container_name: work-sentinel
    networks:
      - work-network
    ports:
      - "8131:8131"
    command:
      - "java"
      - "-Dserver.port=8131"
      - "-Dsentinel.dashboard.auth.username=sentinel"
      - "-Dsentinel.dashboard.auth.password=Qwe54188_"
      - "-Dserver.servlet.session.timeout=86400"
      - "-jar"
      - "app.jar"

  work-elasticsearch:
    # NOTE: ES 的启动及其损耗内存, 因此对其做了限制, 此外由于默认不支持中文, 还需要覆盖内部的配置文件, 以及下载额外的中文分词器插件
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
    container_name: work-elasticsearch
    restart: "always"
    networks:
      - work-network
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=Qwe54188_
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - ELASTIC_CONTAINER=true
    entrypoint:
      - "sh"
      - "-c"
      - "
        \  if [ ! -d /usr/share/elasticsearch/plugins/analysis-ik ]; then
        \    echo 'Installing IK plugin...';
        \    elasticsearch-plugin install --batch https://release.infinilabs.com/analysis-ik/stable/elasticsearch-analysis-ik-7.17.28.zip;
        \  fi;
        \  exec docker-entrypoint.sh\n"

  work-kibana:
    image: docker.elastic.co/kibana/kibana:7.17.28
    container_name: work-kibana
    restart: always
    networks:
      - work-network
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://work-elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=Qwe54188_
      - ELASTIC_CONTAINER=true
    volumes:
      - "./work-basic-component/work-kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"

  work-user-centre:
    build:
      context: ./work-user-centre/
      dockerfile: Dockerfile
    image: work-user-centre:1.0.0
    container_name: work-user-centre
    restart: always
    ports:
      - "8003:8000"
    environment:
      SPRING_PROFILES_ACTIVE: release # 环境变量(可以通过 SPRING_PROFILES_ACTIVE=develop | release | production 修改运行环境的配置)
    networks:
      - work-network

  ## work-smart-cloud
#  work-smart-cloud:
#    build:
#      context: ./work-grad-pick/
#      dockerfile: Dockerfile
#    image: work-user-centre:1.0.0
#    container_name: work-grad-pick
#    restart: always
#    ports:
#      - "8009:8000"
#    environment:
#      SPRING_PROFILES_ACTIVE: release # 环境变量(可以通过 SPRING_PROFILES_ACTIVE=develop | release | production 修改运行环境的配置)
#    networks:
#      - work-network
