# 服务
services:
  ## MySQL
  work-mysql:
    image: mysql:8.0.41
    container_name: work-mysql
    restart: always
    ports: # 等待迁移项目后进行启动
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Qwe54188_
    volumes:
      - "./work-basic-component/work-mysql/memory/:/var/lib/mysql/" # 持久目录
      - "./work-basic-component/work-mysql/share/:/share" # 共享目录
    networks:
      - work-network

  ## Redis
  work-redis:
    image: redis:7.4.2
    container_name: work-redis
    restart: always
    ports: # 等待迁移项目后进行启动
      - "6379:6379"
    environment:
      REDIS_PASSWORD: Qwe54188_
    volumes:
      - "./work-basic-component/work-redis/memory/:/var/lib/redis/" # 持久目录
      - "./work-basic-component/work-redis/share/:/share" # 共享目录
    networks:
      - work-network

  ## Nacos
  work-nacos:
    image: nacos/nacos-server:v2.5.1
    container_name: work-nacos
    restart: always
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      MODE: standalone # 单机部署模式
      NACOS_AUTH_TOKEN: au3y/JinInzSQu5hxaQQSiyvN3kMcfgOLcFRA4AHrUE= # 使用 openssl rand -base64 32 生成
      NACOS_AUTH_IDENTITY_KEY: username
      NACOS_AUTH_IDENTITY_VALUE: root
      NACOS_AUTH_ENABLE: true # 开启权限系统
    networks:
      - work-network

  ## Ubuntu
  work-ubuntu:
    image: ubuntu:22.04
    container_name: work-ubuntu
    restart: always
    ports:
      - "2222:2222"
    tty: true # 必须有这个配置否则无法启动 docker ubuntu
    stdin_open: true # 必须有这个配置否则无法启动 docker ubuntu
    volumes:
      - "./work-basic-component/work-ubuntu/memory/:/memory" # 持久目录
      - "./work-basic-component/work-redis/share/:/share" # 共享目录
    command: /bin/bash
    networks:
      - work-network

  ## work-spring-gateway

  ## work-config-yaml

  ## work-user-centre
  work-user-centre:
    build:
      context: ./work-user-centre/
      dockerfile: Dockerfile
    image: work-user-centre:1.0.0
    container_name: work-user-centre
    restart: always
    ports:
      - "8001:8000"
    environment:
      SPRING_PROFILES_ACTIVE: release # 环境变量(可以通过 SPRING_PROFILES_ACTIVE=develop | release | production 修改运行环境的配置)
    networks:
      - work-network

  ## work-integrated-assess

  ## work-watermark-verifier

  ## work-grad-pick

  ## work-care-flow

  ## work-smart-cloud

# 网络
networks:
  work-network:
    name: work-network
